#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# 2004 (c) MontaVista Software, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= h3600.o
obj-y	+= lowlevel_init.o
